Kalkid/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls", namespace="home")),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views


app_name = "home"

urlpatterns = [
    path('', views.home, name='home'),
    path('fashion', views.fashion, name='fashion'),
    path('electronic', views.electronic, name='electronic'),
    path('jewellery', views.jewellery, name='jewellery'),
    path('contact', views.contact, name='contact'),
    path('buy/', views.buy, name='buy'),
    path('more', views.more, name='more')
    ]

home/models.py
from django.db import models
from django.contrib.auth.models import User


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    
    class Meta:
        abstract = True
       

class Fashion(models.Model):

    phonenumber = models.IntegerField(blank=True, null=True, default=3)
    delivery= models.CharField(max_length=30, blank=True, null=True)
    category = models.CharField(max_length=30, blank=True, null=True)
    
    def __str__(self):
        return self.id

class Category(models.Model):
    name= models.CharField(max_length=30, blank=False, null=False)

    class Meta:
        verbose_name_plural = "Categories"
    
    def __str__(self):
        return str(self.name)
        
class Images(models.Model):
    ''' Images class to hold general images to be used anywhere in the product'''
    images = models.ImageField(upload_to="media")
    titr = models.CharField(max_length=200)
    create = models.DateField(auto_now_add=True)
    update = models.DateField(auto_now=True)

    class Meta:
        def __str__(self):
            return self(self.titr)
            
            
class Product(TimeStamp):#inherit TimeStamp class
    '''This represent an instance of a product to be sold in the market/platform'''
    
    name= models.CharField(max_length=30, blank=False, null=False)
    price = models.FloatField(blank=False, null=False)
    image =  models.ImageField(upload_to="images", blank=True, null=True)#image to be displayed for the product
    description = models.TextField(max_length=220, blank=True)
    
    sold  = models.BooleanField(default=False, blank=True, null=True)
    
    other_image = models.ForeignKey(Images,on_delete=models.CASCADE,blank=True, null=True)#other images that can be displayed along the main image
    category = models.ForeignKey(Category,on_delete=models.CASCADE,blank=True, null=True)
  

    def __str__(self):
        return str(self.name)
    class Meta:
        get_latest_by= "id"


class Shopping(TimeStamp):#inherit TimeStamp class
    '''
    Create an instance of shopping by a buyer
    A single order can have many products and can be assosiated to aa registered user
    '''

    user =models.ForeignKey(User,on_delete=models.CASCADE,blank=True, null=True)
  
  
    def __str__(self):
        return str(self.id)    
        
class Order(TimeStamp):#inherit TimeStamp class
    '''
    Create an instance of order by a buyer
    A single order can have many order
    '''

    shopping = models.ForeignKey(Shopping,on_delete=models.CASCADE,blank=True, null=True)

    def __str__(self):
        return str(self.shopping)   

home/views.py
from django.shortcuts import render, redirect
from .models import Fashion
import os
from django.conf import settings
from .models import Images,Product

     

#image upload
def img(request):
    images = Images.objects.all()
    context = {"images": images}
    return render(request, "electronic.html", "fashion.html", "jewellery.html", context)       
        



def home(request):
    e_prod= Product.objects.filter(category_id=1,sold=False)#.last
    f_prod= Product.objects.filter(category_id=6,sold=False)
    j_prod= Product.objects.filter(category_id=2,sold=False)


  
    # if len(list(e_prod)) >= 3:
    #     last3 = len(list(e_prod))-3
    # else:
    #     last3 = len(list(e_prod))

    # e_prod3=list(e_prod)[last3:]
    
    # print(e_prod)
    
    
    context = {"e_prod":e_prod ,"f_prod":f_prod,"j_prod":j_prod,}

    return render(request, 'index.html', context)
    



def electronic(request):
    e_prod= Product.objects.filter(category_id=1,sold=False)
    context = {"e_prod":e_prod }
 
    return render(request, 'electronic.html', context)

def fashion(request):
    f_prod= Product.objects.filter(category_id=6,sold=False)
    context = {"f_prod":f_prod }
    return render(request, 'fashion.html', context)
   

def jewellery(request):
    j_prod= Product.objects.filter(category_id=2,sold=False)
    context = {"j_prod":j_prod }
   
    return render(request, 'jewellery.html', context)
    
    
  
  
    
def buy(request):
    return render(request, 'buy.html')    
def more(request):
    m_prod= Product.objects.filter(category_id=1,sold=False)
    context = {"m_prod":m_prod }
 
    return render(request, 'more.html')   
    
    #contact page
def contact(request):
     success_massage=""

     if request.method == "POST":
        phonenumber = request.POST.get('phonenumber')
        delivery = request.POST.get('delivery')
        category = request.POST.get('category')
       
        query = Fashion(phonenumber=phonenumber, delivery=delivery, category=category)
        query.save()
        success_massage = "You have sucessfuly send your infomation, You will get within 3 days of your request. Thanks for ordering"
        return render(request, 'contact.html',{"mmg1":success_massage,"mmg2":777})
     return render(request, 'contact.html',{"mmg1":success_massage,"mmg2":777})

   #payment 
def oauth_success(request):
    r = cl.access_token()
    return JsonResponse(r, safe=False)


def lipamimi(request):
    if request.method == "POST":
        phone_number = request.POST.get('phone')
        amount = request.POST.get('amount')
        amount = int(amount)
        account_reference = 'WANYAMA'
        transaction_desc = 'STK Push Description'
        callback_url = stk_push_callback_url
        r = cl.stk_push(phone_number, amount, account_reference, transaction_desc, callback_url)
        return JsonResponse(r.response_description, safe=False)
    return render(request, 'buy.html')

home/templates/home/buy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment page</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    <input type="number" placeholder="Enter Phone Number" name="phone"><br>
    <input type="number" placeholder="Enter Amount" name="amount"><br>


    <input type="submit" value="LIPA">

</form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>FaBrand COMPANY</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
       	 <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="{% static 'https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css' %}">
      <!-- fonts -->
      <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
      <!-- font awesome -->
      <link rel="stylesheet" type="text/css" href="{% static 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %}">
      <!--  -->
      <!-- owl stylesheets -->
      <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
      <link rel="stylesoeet" href="{% static 'css/owl.theme.default.min.css' %}">
      <link rel="stylesheet" href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css' %}" media="screen">
   </head>
   <body>
      <!-- banner bg main start -->
      <div class="banner_bg_main">
         <!-- header top section start -->
         <div class="container">
            <div class="header_section_top">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="custom_menu">
                        <ul>
                           <li><a href="fashion">Fashion</a></li>
                           <li><a href="electronic">Electronic</a></li>
                           <li><a href="jewellery">Jewellery</a></li>
                           <li><a href="contact">Contact</a></li>
                        
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- header top section start -->
         <!-- logo section start -->
         <div class="logo_section">
            <div class="container">
               <div class="row">
                  <div class="col-sm-12">
                     <div class="logo"><a href="index.html"><img src="{% static 'images/logo.png' %}"></a></div>
                     <h3 class="">Menu</h3>
                  </div>
               </div>
         </div>
         <!-- logo section end -->
         <!-- header section start -->
         <div class="header_section">
            <div class="container">
               <div class="containt_main">
                  <div id="mySidenav" class="sidenav">
                     <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                     <a href="">Home</a>
                     <a href="fashion">Fashion</a>
                     <a href="electronic">Electronic</a>
                     <a href="jewellery">Jewellery</a>
                     <a href="contact">Contact</a>
                  
                  </div>
                  <span class="toggle_icon" onclick="openNav()"><img src="{% static 'images/toggle-icon.png' %}"></span>
                    <div>
                  </div>
               </div>
            </div>
         </div>
         <!-- header section end -->
         <!-- banner section start -->
         <div class="banner_section layout_padding">
            <div class="container">
               <div id="my_slider" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                     <div class="carousel-item active">
                        <div class="row">
                           <div class="col-sm-12">
                              <h1 class="banner_taital">Get Start <br>Your favourite shoping</h1>
                             
                           </div>
                        </div>


                  <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
                  <i class="fa fa-angle-left"></i>
                  </a>
                  <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
                  <i class="fa fa-angle-right"></i>
                  </a>
               </div>
            </div>
         </div>
         <!-- banner section end -->
      </div>
      <!-- banner bg main end -->
     
     
     {% block content %}
     
     
     
     
     {% endblock content %}
     
     
      <!-- footer section start -->
      <div class="footer_section layout_padding">
         <div class="container">
            
            <div class="input_bt">
               <input type="text" class="mail_bt" placeholder="Your Email" name="Your Email">
               <span class="subscribe_bt" id="basic-addon2"><a href="#">Subscribe</a></span>
            </div>
            <div class="footer_menu">
               <ul>
                  <li><a href="">Best Sellers</a></li>
                  <li><a href="">Gift Ideas</a></li>
                  <li><a href="">New Releases</a></li>
                  <li><a href="">Today's Deals</a></li>
                  <li><a href="">Customer Service</a></li>
               </ul>
            </div>
            <div class="location_main">Help Line  Number : <a href="#">+2541 1565 8649</a></div>
         </div>
      </div>
      <!-- footer section end -->
      <!-- copyright section start -->
      <div class="copyright_section">
         <div class="container">
            <p class="copyright_text">© 2023 All Rights Reserved. Design by <a href="https://html.design">Alkid web.com</a></p>
         </div>
      </div>
      <!-- copyright section end -->
      <!-- Javascript files-->
      <script src="{% static 'js/jquery.min.js"' %}></script>
      <script src="{% static 'js/popper.min.js"' %}></script>
      <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
      <script src="{% static 'js/plugin.js' %}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
      <script src="{% static 'js/custom.js' %}"></script>
      <script>
         function openNav() {
           document.getElementById("mySidenav").style.width = "250px";
         }
         
         function closeNav() {
           document.getElementById("mySidenav").style.width = "0";
         }
      </script>
   </body>
</html>

templates/buy.html
              
         <!DOCTYPE html>
         <html lang="en">
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"></link>
         <head>
             <meta charset="UTF-8">
             <title>Payment Method</title>
         </head>
         <body>
         
      <div class="container mt-5">
        <div class="row">
            <div class="col-md-4">

         <form action="" method="post">
             {% csrf_token %}
             
                                 <div class="form-group">
                        <input type="Number" class="form-control" placeholder="Enter Phone Number" name="phonenumber" required>
                    </div>

                    <div class="form-group">
                        <input type="number" class="form-control  mt-2" placeholder="Amount" name="amount" required>
                    </div>
         
         <div class="d-grid gap-2">
             <input class="btn btn-success mt-2" type="submit" value="LIPA NA MPESA">
         </div>
         </form>
         <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

         </body>
         </html>     

templates/contact.html
<html lang="en">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"></link>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>contact us</title>
  </head>
  <body>

      <div class="container mt-5">
        <div class="row">
            <div class="col-md-8">
                <h2>Kindly, Order your choise Now</h2>
                
                {{ mmg1 }}
                <form action="{% url 'home:contact' %}" method="post">
                    {% csrf_token %}

                    <div class="form-group">
                        <input type="Number" class="form-control" placeholder="Phone Number" name="phonenumber" required>
                    </div>

                    <div class="form-group">
                        <input type="text" class="form-control  mt-2" placeholder="Place of Delivery" name="delivery" required>
                    </div>
                      
                  <div>
                  <select id="gender" name="category" class="form-control" required>
                            <option selected>select your category</option>
                            <option value="jewellery">jewellery</option>
                           <option value="electronic">electronic</option>
                           <option value="fashion">fashion</option>
                        </select>
            </div>

                    <div class="d-grid gap-2">
                        <button class="btn btn-success mt-2" type="submit">submit</button>
                    </div>
                </form>
            </div>
            
            <div>
            <p> We value your request, we are able to bring you what you have inquire to your place
            </div>
            
                    <tbody class="table-group-divider">
                    {% for d in data %}
                      <tr>
                        <td>{{d.name}}</td>
                        <td>{{d.email}}</td>
                          <td>{{d.phonenumber}}</td>
                       
                    {% endfor %}
                    </tbody>
                  </table>
            </div>
        </div>
      </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>




  </body>

</html>

templates/electronic.html
{% extends "base.html" %}
{% load static %}

     
     {% block content %}
      <!-- electronic section start -->
      <div class="fashion_section">
         <div id="electronic_main_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <h1 class="fashion_taital">Electronic</h1>
                     
                     <div class="fashion_section_2">
                        <div class="row">
                        
                        
                     
                        {% for prod in e_prod%}
                        
                        
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">{{prod.name}}</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">Ksh {{prod.price}}</span></p>
                                 <div class="electronic_img"><img src="{% static 'images/laptop-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="buy">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="more">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           
                         {% endfor %}
                           
                           
                     
                           
                           
              
                        </div>
                     </div> <!-- fashion_section_2 -->
                     
                     
                  </div>
               </div>
              
            <a class="carousel-control-prev" href="#electronic_main_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#electronic_main_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
            </a>
         </div>
      </div>
      <!-- electronic section end -->
      {% endblock content %}
     

templates/fashion.html
{% extends "base.html" %}
{% load static %}

     
     {% block content %}

      <!-- fashion section start -->
      <div class="fashion_section">
         <div id="main_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <h1 class="fashion_taital">Man & Woman Fashion</h1>
                     <div class="fashion_section_2">
                        <div class="row">
                        
                        
                        {% for prod in f_prod%}
                        
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">{{prod.name}}</h4>
                                 <p class="price_text">Price  <span style="color: #262626;">Ksh {{prod.price}}</span></p>
                                 <div class="tshirt_img"><img src="{% static 'images/tshirt-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="buy">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="more">See More</a></div>
                                 </div>
                                
                              </div>
                           </div>
                           
                            {% endfor %}
             
                           
                        </div>
                     </div>
                  </div>
               </div>
               
               
               
            <a class="carousel-control-prev" href="#main_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#main_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
            </a>
         </div>
      </div>
      <!-- fashion section end -->


    {% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load static %}

     
     {% block content %}
     <!-- fashion section start -->
      <div class="fashion_section">
      
         <div id="main_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <h1 class="fashion_taital">Man & Woman Fashion</h1>
                     <div class="fashion_section_2">
                        <div class="row">
                        
                         {% for prod in f_prod%}
                         
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">{{prod.name}}</h4>
                                 <p class="price_text">Price  <span style="color: #262626;">Ksh {{prod.price}}</span></p>
                                 <div class="tshirt_img"><img src="{% static 'images/tshirt-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="buy">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="more">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           {% endfor %}
                     
                        </div>
                     </div>
                  </div>
               </div>
              
            <a class="carousel-control-prev" href="#main_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#main_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
            </a>
         </div>
      </div>
      <!-- fashion section end -->
      <!-- electronic section start -->
      <div class="fashion_section">
         <div id="electronic_main_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <h1 class="fashion_taital">Electronic</h1>
                     <div class="fashion_section_2">
                        <div class="row">
                        
                        
                        
                        {% for prod in e_prod%}
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">{{prod.name}}</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">Ksh {{prod.price}}</span></p>
                                 <div class="electronic_img"><img src="{% static 'images/laptop-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="buy">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="more">See More</a></div>
                                 </div>
                              </div>
                           </div>
                            {% endfor %}
                            
                  
                        </div>
                     </div>
                  </div>
               </div>
              
            <a class="carousel-control-prev" href="#electronic_main_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#electronic_main_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
            </a>
         </div>
      </div>
      <!-- electronic section end -->
      <!-- jewellery  section start -->
      <div class="jewellery_section">
     
         <div id="jewellery_main_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <h1 class="fashion_taital">Jewellery Accessories</h1>
                     <div class="fashion_section_2">
                        <div class="row">
                        
                        {% for prod in j_prod%}
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">{{prod.name}}</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">Ksh  {{prod.price}}</span></p>
                                 <div class="jewellery_img"><img src="{% static 'images/jhumka-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="buy">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="more">See More</a></div>
                                 </div>
                              </div>
                           </div>
                            {% endfor %}
                            
                            
                   
                        </div>
                     </div>
                  </div>
               </div>
              
            <a class="carousel-control-prev" href="#jewellery_main_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#jewellery_main_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
            </a>
            <div class="loader_main">
               <div class="loader"></div>
            </div>
         </div>
      </div>
      <!-- jewellery  section end -->

     
     
     
     {% endblock content %}
     

      

templates/jewellery.html
{% extends "base.html" %}
{% load static %}

     
     {% block content %}
      <!-- jewellery  section start -->
      <div class="jewellery_section">
         <div id="jewellery_main_slider" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <div class="container">
                     <h1 class="fashion_taital">Jewellery Accessories</h1>
                     <div class="fashion_section_2">
                        <div class="row">
                        
                        
                        {% for prod in j_prod%}
                        
                           <div class="col-lg-4 col-sm-4">
                              <div class="box_main">
                                 <h4 class="shirt_text">{{prod.name}}</h4>
                                 <p class="price_text">Start Price  <span style="color: #262626;">Ksh {{prod.price}}</span></p>
                                 <div class="jewellery_img"><img src="{% static 'images/jhumka-img.png' %}"></div>
                                 <div class="btn_main">
                                    <div class="buy_bt"><a href="buy">Buy Now</a></div>
                                    <div class="seemore_bt"><a href="more">See More</a></div>
                                 </div>
                              </div>
                           </div>
                           
                           
                           {% endfor %}
                 
                   
                        </div>
                     </div>
                  </div>
               </div>
               
            <a class="carousel-control-prev" href="#jewellery_main_slider" role="button" data-slide="prev">
            <i class="fa fa-angle-left"></i>
            </a>
            <a class="carousel-control-next" href="#jewellery_main_slider" role="button" data-slide="next">
            <i class="fa fa-angle-right"></i>
            </a>
            <div class="loader_main">
               <div class="loader"></div>
            </div>
         </div>
      </div>
      <!-- jewellery  section end -->
   
      {% endblock content %}